apiVersion: v1
kind: Service
metadata:
  name: mesh-control-plane
  namespace: mesh
  labels:
    app: mesh-control-plane
spec:
  selector:
    app: mesh-control-plane
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
